#!/bin/sh

set -e

XDHOME='/var/lib/XD'
XDUSER='debian-xd'

if [ "$1" != "configure" ]; then
    exit 0
fi

if [ ! -e "${XDHOME}/xd.ini" ]; then
    cd $XDHOME && sudo -u $XDUSER XD --genconf ${XDHOME}/xd.ini
fi

#DEBHELPER#

exit 0
